shop/cart/urls.py
from django.urls import path
from .import views

app_name = 'cart'

urlpatterns = [

    path('', views.cartView, name='cart'),
    path('add/', views.addToCart , name='add'),
    path('delete/<int:product_id>/<int:qty>', views.deleteCartItem , name='delete'),
    path('remove/', views.removeCart, name='remove'),
    path('order/add/<int:cart_id>', views.addOrder, name='add_order')

]

shop/main/urls.py
from django.urls import path
from .import views


app_name = 'main'

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('detail/<slug>',views.ProductDetailView.as_view(),name='detail'),
    path('category/detail/<slug>',views.CategoryDetailView.as_view(),name='category_detail'),
    path('accounts/profile/', views.profile, name='profile'),
    path('searchs/',views.searchResults, name='searchs'),

]

shop/shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='shop')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('accounts/', include('allauth.urls')),



   
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,  document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,  document_root=settings.MEDIA_ROOT)

shop/cart/models.py
from django.db import models
from main.models import Product
# Create your models here.

class CardProduct(models.Model):
    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
        related_name='cart_products'
    )
    quantity = models.PositiveIntegerField(default=0)
    price = models.PositiveIntegerField(default=0)

    def __str__(self):
        return str(self.product.name)


class Cart(models.Model):
    products = models.ManyToManyField(CardProduct, related_name='products')
    total_quantity = models.PositiveIntegerField(default=0)
    total_price = models.PositiveIntegerField(default=0)

    def add(self,product_id,qty):
        product = Product.objects.get(id=product_id)
        price = product.price * qty
        self.products.create(
            product=product,
            quantity=qty,
            price=price
        )
        self.total_quantity += qty
        self.total_price += price
        self.save()
        return True

    def deleteItem(self, product_id,qty):
        product = Product.objects.get(id=product_id)
        p_id = product.id
        for item in self.products.all():
            if item.product.id == p_id:
                item.delete()
        price = product.price * qty
        # self.products.remove(product)
        self.total_quantity -= qty
        self.total_price -= price
        self.save()
        return True


    def __str__(self):
        return f"Cart = {self.id}"
    

class OrderProduct(models.Model):
    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
        related_name='order_product'
    )
    quantity = models.PositiveIntegerField(default=0)
    price = models.PositiveIntegerField(default=0)

    def __str__(self):
        return str(self.product.name)

class Order(models.Model):
    products = models.ManyToManyField(OrderProduct, related_name='order_products')
    name = models.CharField(max_length=200)
    address = models.CharField(max_length=200)
    phone = models.PositiveIntegerField(default=0)
    payed = models.BooleanField(default=False)

    def __str__(self):
        return str(self.name)

shop/cart/forms.py
from django import forms
from .models import Order

class AddOrderForm(forms.ModelForm):

    class Meta:
        model = Order
        fields = ['name', 'address','phone']

shop/cart/views.py
from django.shortcuts import render,redirect
from .models import *
from main.models import Product
from django.http import JsonResponse, HttpResponse
from .forms import AddOrderForm

# Create your views here.
def cart_init(request):
    try:
        cart = Cart.objects.get(id=request.session.get('user_cart_id'))
    except:
        cart = Cart.objects.create()
        request.session['user_cart_id'] = cart.id
    return cart



def cartView(request):
    return render(request, 'cart.html')

import json
def addToCart(request):
    d = request.GET.get('data')
    data  = json.loads(d)
    print(data)
    product_id = data['product_id']
    quantity = data['count']
    cart = cart_init(request)
    cart.add(product_id,quantity)
    status = {

    }
    if cart:
        status['success'] = 200
    else:
        status['error'] = 400
    return JsonResponse(status)

def deleteCartItem(request,product_id,qty):
    cart = Cart.objects.get(id=request.session.get('user_cart_id'))
    cart.deleteItem(product_id,qty)
    return redirect('cart:cart')

def removeCart(request):
    print(request.path)
    try:
        cart = Cart.objects.get(id=request.session.get('user_cart_id'))
    except:
        return redirect('main:home')
    cart.delete()
    return redirect('main:home')

def addOrder(request,cart_id):
    cart = Cart.objects.get(id=cart_id)
    if request.method == 'POST':
        form = AddOrderForm(request.POST)
        if form.is_valid():
           order =  form.save()
           for p in cart.products.all():
               order.products.create(
                   product=p.product,
                   quantity=p.quantity,
                   price=p.quantity * p.price
               )
           order.payed = False
           order.save()
           last_order = Order.objects.last()
           return render(request, 'order_done.html', {'order': last_order})
    else:
        form = AddOrderForm()
    # pass
    return render(request,'order.html',{'form':form} )

shop/templates/cart.html
{% extends "wrapper.html" %}
{% load static %}
{% block content %}
  

    <!-- Page Title -->
    <section class="page-title text-center">
      <div class="container">
        <h1 class=" heading page-title__title">Savatcha</h1>
      </div>
    </section> <!-- end page title -->


    <!-- Cart -->
    <section class="section-wrap cart pt-50 pb-40">
      <div class="container relative">
        {% if not cart.products %} 
        <div class="alert alert-danger m-5 w-5">
          <h1 align="center">Tovarlar topilmadi !</h1>
        </div>
        {% endif %}
        <div class="table-wrap">
          <table class="shop_table cart table">
            <thead>
              <tr>
                <th class="product-name" colspan="2">Tovar</th>
                <th class="product-price">Tovar narxi</th>
                <th class="product-quantity">Tovar soni</th>
                <th class="product-subtotal" colspan="2">Umumiy narxi</th>
              </tr>
            </thead>
            <tbody>

              <tr class="cart_item">
              {% for product in cart.products.all %}
                {% with product as item %}
                <td class="product-thumbnail">
                  <a href="#">
                    <img src="{{item.product.image.url}}" alt="">
                  </a>
                </td>
                <td class="product-name">
                  <a href="{% url 'main:detail' product.id %}">{{item.product.name}}</a>
                </td>
                <td class="product-price">
                  <span class="amount">$<strong>{{item.product.price}}</strong></span>
                </td>
                <td class="product-quantity">
                 <span class="amount">{{item.quantity}}</span>
                </td>
                <td class="product-subtotal">
                  <span class="amount">$<strong>{{item.price}}</strong></span>
                </td>
                <td class="product-remove">
                  <a href="{% url 'cart:delete' item.product.id item.quantity %}" class="remove" title="Remove this item">
                    <i class="ui-close"></i>
                  </a>
                </td>
              </tr>
                {% endwith %}
          {% endfor %}
               <tfoot  >
                       <tr>
                         <td>
                              <button style="background-color: red; border-radius: 50px;">
                              <a href="{% url 'cart:remove'  %}" style="color: white;" >
                                  <b>Savatchani tozalash</b>
                                  <i class="fas fa-trash"></i>
                              </a>
                              </button>
                         </td>
                     </tr>
                  </tfoot>

        
            </tbody>
          </table>
        </div>
          <div class="row">
                <div class="col-md-6">
                    <div class="container">
                    <div class="card p-5">
                        <div class="mt-2 alert alert-danger">
                            <h4>Barcha tovarlar :
                                {% if cart.total_quantity %}
                                <strong>{{ cart.total_quantity }}</strong>
                                {% else %}
                                    <strong>0</strong>
                                {% endif %}

                                ta</h4>
                      
                        <div class="mt-2 alert alert-danger">
                            <h4>Umumiy summa : $
                                {% if cart.total_price  %}
                                 <strong>{{ cart.total_price }}</strong>
                                {% else %}
                                     <strong>0</strong>
                                {% endif %}

                            </h4>
                        {% if cart.products %}
                        <button style="background-color: black; border-radius: 10px;">
                        <a href="{% url 'cart:add_order' cart.id %}" style="color:white;">
                            <b>Buyurtma</b>
                        </a>
                        </button>
                        {% endif %}
                              </div>
                        </div>
                        </div>
                    </div>
                </div>
           
            </div>

        
      </div> <!-- end container -->
    </section> <!-- end cart -->

{% endblock  %}

shop/templates/category.html
{% extends "wrapper.html" %}
{% load static %}
{% block content %}

    <section class="section-wrap pb-20 product-single">
      <div class="container">

        <!-- Breadcrumbs -->
      
        <ol class="breadcrumbs">
          <li>
            <a href="{% url 'main:home' %}"><b>Bosh sahifa</b></a>
          </li>
          <li>
            <a href="{% url 'main:category_detail' object.slug %}">{{object.name}}</a>
          </li>
        </ol>
        
       
      </div> <!-- end container -->
    </section> <!-- end single product -->
<br><br><br><br>
<section class="section-wrap no-padding">
      <div class="container">
        <div class="heading-row">
          <div class="text-center">
            <h2 class="heading bottom-line">
              {{object.name}}
            </h2>
          </div>
        </div>

        <div class="row row-8">
          {% for post in object.products.all %}
          <div class="col-lg-2 col-sm-4 product">
            <div class="product__img-holder">
              <a href="{% url 'main:detail' post.slug %}" class="product__link" aria-label="Product">
                <img src="{{post.image.url}}" alt="" class="product__img">
              </a>
              <div class="product__actions">
                <a href="quickview.html" class="product__quickview">
                  <i class="ui-eye"></i>
                  <span>{{post.views}}</span>
                </a>
                <a href="#" onclick="AddToCart({{ post.id }})" class="product__add-to-wishlist">
                  <i class="ui-heart"></i>
                  <span>Savatchaga qo'shish</span>
                </a>
              </div>
            </div>

            <div class="product__details">
              <h3 class="product__title">
                <a href="{% url 'main:detail' post.slug %}">{{post.name}}</a>
              </h3>
            </div>

           <span class="product__price">
              <ins>
                <span class="amount">${{post.price}}</span>
              </ins>
              <del>
                <span>${{post.old_price}}</span>
              </del>
            </span>
          </div> <!-- end product -->
        {% endfor %}
        </div> <!-- end row -->
      </div> <!-- end container -->
    </section> <!-- end new arrivals -->

{% endblock  %}

shop/templates/login.html
<div class="sign-in-popup">
  <div class="row">
    <div class="col-md-6 mb-30">
      <h3>Sign In</h3>
      <form action="">
        <label for="sign-in-input">Username or email address <abbr class="required" title="required">*</abbr></label>
        <input type="text" name="email" id="sign-in-input">

        <label for="sign-in-password">Password <abbr class="required" title="required">*</abbr></label>
        <input type="text" name="password" id="sign-in-password">

        <input type="submit" name="sign-in" value="Sign In" class="btn btn-md btn-dark btn-button">

        <a href="#" class="sign-in-popup__forgot-password">Forgot Password?</a>
      </form>
    </div>
    <div class="col-md-6 mb-30">
      <h3>Register</h3>
      <form action="">
        <label for="register-input">Email address <abbr class="required" title="required">*</abbr></label>
        <input type="text" name="email" id="register-input">

        <label for="password">Password <abbr class="required" title="required">*</abbr></label>
        <input type="password" name="password" id="register-password">

        <input type="submit" name="register" value="Register" class="btn btn-md btn-dark btn-button">
      </form>
    </div>
  </div>
</div>

shop/templates/single-product.html
{% extends "wrapper.html" %}
{% load static %}
{% block content %}
  

    <!-- Single Product -->
    <section class="section-wrap pb-20 product-single">
      <div class="container">

        <!-- Breadcrumbs -->
        <ol class="breadcrumbs">
          <li>
            <a href="{% url 'main:home' %}">Bosh sahifa</a>
          </li>
          <li>
            <a href="{% url 'main:category_detail' object.category.slug %}">{{object.category}}</a>
          </li>
          <li class="active">
            {{object.name}}
          </li>
        </ol>

        <div class="row">

          <div class="col-md-6 product-slider mb-50">

            <div class="flickity flickity-slider-wrap mfp-hover" id="gallery-main">
              {% for obj_img in object.product_images.all %}
              <div class="gallery-cell">
                <a href="{{obj_img.image.url}}" class="lightbox-img">
                  <img src="{{obj_img.image.url}}" alt="" />
                </a>
              </div>
              {% endfor %}
            </div> <!-- end gallery main -->

            <div class="gallery-thumbs" id="gallery-thumbs">
            {% for obj_img in object.product_images.all %}
              <div class="gallery-cell">
                <img src="{{obj_img.image.url}}" alt="" />
              </div>
            {% endfor %}
            </div> <!-- end gallery thumbs -->
          </div> <!-- end col img slider -->

          <div class="col-md-6 product-single">
            <h1 class="product-single__title uppercase">{{object.name}}</h1>

            <span class="product-single__price">
              <ins>
                <span class="amount">${{object.price}}</span>
              </ins>
              <del>
                <span>${{object.old_price}}</span>
              </del>
            </span>            

            <div class="colors clearfix">
              <span class="colors__label">Rangi: <span class="colors__label-selected">{{object.colors}}</span></span>
              <a href="#" class="colors__item colors__item--selected {{object.colors}}"></a>
              {% for color in object.other_colors.all %}
              <a href="#" class="colors__item {{color}}"></a>  
              {% endfor %}
            </div>

            <div class="size-quantity clearfix">
              <div class="size">
                <label>Razmer</label>
                <select name="size" id="size__select" class="size__select">
                  <option value="xs">XS</option>
                  <option value="s">S</option>
                  <option value="m">M</option>
                  <option value="l">L</option>
                  <option value="xl">XL</option>
                </select>
              </div>
              
              <div class="quantity">
                <label>Soni</label>                 
                <select name="quantity" id="product_qty" class="quantity__select">
                  <option value="1">1 dona</option>
                  <option value="2">2 dona</option>
                  <option value="3">3 dona</option>
                  <option value="4">4 dona</option>
                  <option value="5">5 dona</option>
                </select>
              </div>
            </div>            

            <div class="row row-10 product-single__actions clearfix">
              <div class="col">
                <a href="#" onclick="AddToCart({{ object.id }})" class="btn btn-lg btn-color product-single__add-to-cart">
                  <i class="ui-bag"></i>
                  <span>Savatchaga qo'shish</span>
                </a>
              </div>
              <div class="col">
                <a href="{% url 'cart:cart' %}" class="btn btn-lg btn-dark product-single__add-to-wishlist">
                  <i class="ui-bag"></i>
                  <span>Savatchaga o'tish</span>
                </a>
              </div>
            </div>            
            <!-- Accordion -->
            <div class="accordion mb-50" id="accordion">
              <div class="accordion__panel">
                <div class="accordion__heading" id="headingOne">
                  <a data-toggle="collapse" href="#collapseOne" class="accordion__link accordion--is-open" aria-expanded="true" aria-controls="collapseOne">Tovar haqida<span class="accordion__toggle">&nbsp;</span>
                  </a>
                </div>
                <div id="collapseOne" class="collapse show" data-parent="#accordion" role="tabpanel" aria-labelledby="headingOne">
                  <div class="accordion__body">
                   {{ object.description}}
                  </div>
                </div>
              </div>

              <div class="accordion__panel">
                <div class="accordion__heading" id="headingTwo">
                  <a data-toggle="collapse" href="#collapseTwo" class="accordion__link accordion--is-closed" aria-expanded="false" aria-controls="collapseTwo">Information<span class="accordion__toggle">&nbsp;</span>
                  </a>
                </div>
                <div id="collapseTwo" class="collapse" data-parent="#accordion" role="tabpanel" aria-labelledby="headingTwo">
                  <div class="accordion__body">
                    <table class="table shop_attributes">
                      <tbody>
                        <tr>
                          <th>Kategoriya:</th>
                          <td>{{object.category}}</td>
                        </tr>
                        <tr>
                          <th>Omborda:</th>
                          <td>{% if object.instock %}<strong>BOR</strong>{% else %}
                            <strong>YO'Q</strong>
                          {% endif %}</td>
                        </tr>
                        <tr>
                          <th>Soni:</th>
                          <td>{{object.count}}</td>
                        </tr>                                     
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div> <!-- end accordion -->

          </div> <!-- end col product description -->
        </div> <!-- end row -->
       
      </div> <!-- end container -->
    </section> <!-- end single product -->


    <!-- Related Products -->
    <section class="section-wrap pt-0 pb-40">
      <div class="container">

        <div class="heading-row">
          <div class="text-center">
            <h2 class="heading bottom-line">
             Boshqa Tovarlar
            </h2>
          </div>
        </div>

          <div class="row row-8">
          {% for post in posts %}
          <div class="col-lg-2 col-sm-4 product">
            <div class="product__img-holder">
              <a href="{% url 'main:detail' post.slug %}" class="product__link" aria-label="Product">
                <img src="{{post.image.url}}" alt="" class="product__img">
              </a>
              <div class="product__actions">
                <a href="quickview.html" class="product__quickview">
                  <i class="ui-eye"></i>
                  <span>{{post.views}}</span>
                </a>
                <a href="#" onclick="AddToCart({{ object.id }})" class="product__add-to-wishlist">
                  <i class="ui-heart"></i>
                  <span>Savatchaga qo'shish</span>
                </a>
              </div>
            </div>

            <div class="product__details">
              <h3 class="product__title">
                <a href="{% url 'main:detail' post.slug %}">{{post.name}}</a>
              </h3>
            </div>

           <span class="product__price">
              <ins>
                <span class="amount">${{post.price}}</span>
              </ins>
              <del>
                <span>${{post.old_price}}</span>
              </del>
            </span>
          </div> <!-- end product -->
        {% endfor %}
        </div> <!-- end row -->
    
        </div> <!-- end row -->
      </div> <!-- end container -->
    </section> <!-- end related products -->

  {% endblock  %}

shop/templates/wrapper.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Asralkhanov | Shop</title>

  <meta charset="utf-8">
  <!--[if IE]><meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'><![endif]-->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <meta name="description" content="">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" />

  <!-- Google Fonts -->
  <link href='http://fonts.googleapis.com/css?family=Questrial:400%7CMontserrat:300,400,700,700i' rel='stylesheet'>
  <link rel="short icon" href="https://icons.iconarchive.com/icons/graphicloads/100-flat/128/cart-icon.png">
  <!-- Css -->
  <link rel="stylesheet" href="/static/css/bootstrap.min.css" />
  <link rel="stylesheet" href="/static/css/font-icons.css" />
  <link rel="stylesheet" href="/static/css/style.css" />
  <link rel="stylesheet" href="/static/css/color.css" />

  <!-- Favicons -->


</head>

<script>
  if ( window.history.replaceState ) {
  window.history.replaceState( null, null, window.location.href );
  }
</script>

<body>

  <!-- Preloader -->
  <div class="loader-mask">
    <div class="loader">
      <div></div>
    </div>
  </div>
  

  <!-- Mobile Sidenav -->    
  <header class="sidenav" id="sidenav">
    <!-- Search -->
    <div class="sidenav__search-mobile">
      <form method="get" class="sidenav__search-mobile-form">
        <input type="search" class="sidenav__search-mobile-input" placeholder="Search..." aria-label="Search input">
        <button type="submit" class="sidenav__search-mobile-submit" aria-label="Submit search">
          <i class="ui-search"></i>
        </button>
      </form>
    </div>

    <nav>
      <ul class="sidenav__menu" role="menubar">
        {% for category in categories %}
        <li>
          <a href="{% url 'main:category_detail' category.slug %}" class="sidenav__menu-link">{{category.name}}</a>
        </li>
        {% endfor %}
        <li>
          {% if request.user.is_authenticated %}
          <a href="{% url 'account_logout' %}" class="sidenav__menu-link">Ciqish</a>
          {% else %}
          <a href="{% url 'account_login' %}" class="sidenav__menu-link">Kirish</a>
          {% endif %}
        </li>
      </ul>
    </nav>
  </header> <!-- end mobile sidenav -->


  <main class="main oh" id="main">

    <!-- Navigation -->
    <header class="nav">

      <div class="nav__holder nav--sticky">
        <div class="container relative">

          <!-- Top Bar -->
          <div class="top-bar d-none d-lg-flex">

            <!-- Currency / Language -->
            <ul class="top-bar__currency-language">
              <li class="top-bar__language">
                <a href="#">Uzbek</a>
              </li>
              <li class="top-bar__currency">
                <a href="#">USD</a>
              </li>              
            </ul>

            <!-- Promo -->

            <!-- Sign in / Wishlist / Cart -->
            <div class="top-bar__right">

              <!-- Sign In -->
          {% if request.user.is_authenticated %}
          <a href="{% url 'account_logout' %}" class="top-bar__item" > <i class="fas fa-user"></i> {{request.user.username}}</a>
          <a href="{% url 'account_logout' %}" class="top-bar__item" ><i class="fas fa-sign-in-alt"></i>Chiqish</a>
          {% else %}
          <a href="{% url 'account_login' %}" class="top-bar__item "><i class="ui-user"></i>Kirish</a>
          {% endif %}

              <div class="top-bar__item nav-cart">                
                <a href="{% url 'cart:cart' %}">
                  <i class="ui-bag"></i>
                  {% if cart.products%}
                    <span class="nav-link-notification-number">
                        {{ cart.products.count }}
                    </span>
                {% else %}
                     <span class="nav-link-notification-number">
                        0
                    </span>
                {% endif %}
                </a>
                <div class="nav-cart__dropdown">
                  <div class="nav-cart__items">
                    {% for item in cart.products.all %}                   
                    <div class="nav-cart__item clearfix">
                      <div class="nav-cart__img">
                        <a href="{% url 'main:detail' item.product.slug %}">
                          <img src="{{item.product.image.url}}" alt="">
                        </a>
                      </div>
                      <div class="nav-cart__title">
                        <a href="{% url 'main:detail' item.product.slug %}">
                         {{item.product.name}}
                        </a>
                        <div class="nav-cart__price">
                          <span>{{item.quantity}} x</span>
                          <span>${{item.product.price}}</span>
                        </div>
                      </div>
                      <div class="nav-cart__remove">
                        <a href="{% url 'cart:remove' %}"><i class="ui-close"></i></a>
                      </div>
                    </div>
                     {% endfor %}
                
                  </div> <!-- end cart items -->
                  <div class="nav-cart__actions mt-20">
                    <a href="{% url 'cart:cart' %}" class="btn btn-md btn-light"><span>Savatchaga o'tish</span></a>
                  </div>
                </div>
              </div>
            </div>

          </div> <!-- end top bar -->

          <div class="flex-parent">

            <!-- Mobile Menu Button -->
            <button class="nav-icon-toggle" id="nav-icon-toggle">
              <span class="nav-icon-toggle__box">
                <span class="nav-icon-toggle__inner"></span>
              </span>
            </button> <!-- end mobile menu button -->

            <!-- Logo -->
            <a href="{% url 'main:home' %}" class="logo">
              <span style="color: white;">AsralkhanovShop</span>
            </a>

            <!-- Nav-wrap -->
            <nav class="flex-child nav__wrap d-none d-lg-block">              
              <ul class="nav__menu">
                {% for category in categories %}
                <li class="nav__dropdown active">
                  <a href="{% url 'main:category_detail' category.slug %}">{{category.name}}</a>
                </li>
                {% endfor %}
              </ul> <!-- end menu -->

            </nav> <!-- end nav-wrap -->


            <!-- Search -->
            <div class="flex-child nav__search d-none d-lg-block">
              <form id="search_form" name="gs" method="GET" action="{% url 'main:searchs' %}" class="nav__search-form">
                <input type="text" name="query" class="nav__search-input" placeholder="Qidirish...." autocomplete="on">
                  <i class="ui-search"></i>                
              </form>
            </div>


            <!-- Mobile Wishlist -->
            <a href="#" class="nav__mobile-wishlist d-lg-none">
              <i class="ui-heart"></i>
            </a>

            <!-- Mobile Cart -->
            <a href="cart.html" class="nav__mobile-cart d-lg-none">
              <i class="ui-bag"></i>
              <span class="nav__mobile-cart-amount">(2)</span>
            </a>
        
          </div> <!-- end flex-parent -->
        </div> <!-- end container -->

      </div>
    </header> <!-- end navigation -->



{% block content %}
{% endblock %}




 <!-- Footer -->
    <footer class="footer">
      <div class="container">
        <div class="footer__widgets">
          <div class="row">

            <div class="col-lg-2 col-md-6">
              <div class="widget widget_nav_menu">
                <h4 class="widget-title white">AsralkhanovShop</h4>
                <ul>
                  {% for category in  categories %}
                  <li><a href="{% url 'main:category_detail' category.slug %}">{{category.name}}</a></li>
                  {% endfor %}
                </ul>
              </div>
            </div>

          </div>
        </div>    
      </div> <!-- end container -->

      <div class="footer__bottom">
        <div class="container">
          <div class="row">
            <div class="col-md-6 text-sm-center">
              <span class="copyright">
                &copy; 2021 AsralkhanovShop <a href="#">Asralkhanov</a>
              </span>
            </div>
          </div>
        </div>
      </div> <!-- end bottom footer -->
    </footer> <!-- end footer -->

    <div id="back-to-top">
      <a href="#top"><i class="ui-arrow-up"></i></a>
    </div>

  </main> <!-- end main-wrapper -->


  
  <!-- jQuery Scripts -->
  <script type="text/javascript" src="/static/js/jquery.min.js"></script>
  <script type="text/javascript" src="/static/js/bootstrap.min.js"></script>
  <script type="text/javascript" src="/static/js/easing.min.js"></script>
  <script type="text/javascript" src="/static/js/jquery.magnific-popup.min.js"></script>
  <script type="text/javascript" src="/static/js/owl-carousel.min.js"></script>  
  <script type="text/javascript" src="/static/js/flickity.pkgd.min.js"></script>
  <script type="text/javascript" src="/static/js/modernizr.min.js"></script>
  <script type="text/javascript" src="/static/js/scripts.js"></script>
  <script type="text/javascript" src="/static/cart.js"></script>

</body>
</html>